### ISSUE TITLE
Error training deepfilter

### ISSUE THREAD

**Issue by damirkotoric** [algorithmiaio/deepfilter-training#2]
Hi, I completed the steps 1.1 - 1.6 of your README, but when I run `th train.lua -data dataset -style_image style.jpg -style_size 480 -image_size 480 -model johnson -batch_size 4 -learning_rate 1e-2 -style_weight 10 -style_layers relu1_2,relu2_2,relu3_2,relu4_2 -content_layers relu4_2 -gpu 1` as indicated in step 1.7, I get:

![image](https://user-images.githubusercontent.com/520622/37662339-2acecc4a-2c57-11e8-9943-30d8bdb330d9.png)

To give you an idea of the environment, if I run `ls -al` I get:

![image](https://user-images.githubusercontent.com/520622/37662390-42d8f676-2c57-11e8-85d0-a64aa7f38360.png)

I tried rerunning step 1.4 `. deepfilter-training/install_environment.sh` hoping this might do the trick, but I get the same error. I'm running an p2.xlarge AWS instance as required:

![image](https://user-images.githubusercontent.com/520622/37662550-99c0e11a-2c57-11e8-8330-f748eda53056.png)

Could you please help me debug this problem?

**Comment by besirkurtulmus** [comment]
It looks like you're not in the correct directory. Can you first `cd texture_nets` and re-run your command again?

**Comment by damirkotoric** [comment]
@besirkurtulmus Thanks! That worked. It would be worth adding that in the documentation between the current step 1.6 and 1.7.

**Comment by besirkurtulmus** [comment]
Weird. If you followed the instructions in the documentation, you should have been in the correct directory.

Did you follow the instructions step by step? (This includes the `.` before running `deepfilter-training/install_environment.sh`)

**Comment by damirkotoric** [comment]
As far as I'm aware I didn't make any mistakes, but it's possible. Anyway, that's solved the issue. Thanks very much for helping out.

**Comment by besirkurtulmus** [comment]
I still think that you may have omitted the `.` before the command :)

For more about it, refer to [this](https://unix.stackexchange.com/questions/114300/whats-the-meaning-of-a-dot-before-a-command-in-shell).

If not, I wanna double check the installation script.
